// Catálogo oficial de instrumentos del PER. Datos puros, sin lógica — los usa tanto el seed
// demo completo (prisma/seed.ts) como el bootstrap seguro de producción
// (prisma/seed-bootstrap.ts), para no mantener dos copias del mismo catálogo.

export const EFFECTIVE_FROM = new Date("2026-03-01T00:00:00Z");

export const SETTINGS_CATALOG = [
  { key: "alert_days_vinculacion", value: "10" },
  { key: "alert_days_conexion", value: "14" },
  { key: "alert_days_finalizacion", value: "10" },
  { key: "alert_days_validacion_pendiente", value: "5" },
  { key: "duration_months_vinculacion", value: "1" },
  { key: "duration_months_conexion", value: "6" },
  { key: "duration_months_finalizacion", value: "2" },
];

/**
 * `createdByUserId` depende de qué Admin exista en cada base (distinto en el seed demo vs. el
 * bootstrap de producción), por eso el catálogo se arma con una función en vez de un array
 * estático.
 */
export function buildInstrumentCatalog(createdByUserId: string) {
  return [
    // Fuera del itinerario de caso (stageId: null) — se mantienen tal cual estaban.
    {
      name: "Inducción y Caracterización PER",
      description: "Recopilación de antecedentes iniciales de los PER",
      type: "GOOGLE_FORM",
      googleUrl: "https://docs.google.com/forms/d/e/1FAIpQLSf123_induccion_per/viewform",
      phaseId: "FASE_1",
      stageId: null,
      order: 0,
      activityKey: null,
      submissionMode: "EXTERNAL_LINK",
      optional: false,
      triggerCondition: "SEQUENTIAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: true,
      criticalTask: false,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_induccion_per",
    },
    {
      name: "Formulario de Preinscripción PA",
      description: "Preinscripción de candidatas en Fase 2",
      type: "GOOGLE_FORM",
      googleUrl: "https://docs.google.com/forms/d/e/1FAIpQLSf456_preinscripcion_pa/viewform",
      phaseId: "FASE_2",
      stageId: null,
      order: 0,
      activityKey: null,
      submissionMode: "EXTERNAL_LINK",
      optional: false,
      triggerCondition: "SEQUENTIAL",
      targetRole: "COORDINATOR",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: true,
      criticalTask: false,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_preinscripcion_pa",
    },
    {
      name: "Acta de Primer Encuentro y Encuadre",
      description: "Registro de conformación y primer encuentro de la dupla",
      type: "GOOGLE_DOC",
      googleUrl: "https://docs.google.com/document/d/1_acta_primer_encuentro/edit",
      phaseId: "FASE_3",
      stageId: null,
      order: 0,
      activityKey: null,
      submissionMode: "EXTERNAL_LINK",
      optional: false,
      triggerCondition: "SEQUENTIAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: true,
      criticalTask: true,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_acta_primer_encuentro",
    },
    {
      name: "Itinerario de Acompañamiento Personalizado (IAP)",
      description: "Documento paraguas del IAP (el contenido real vive en las Actividades 1-4 del itinerario)",
      type: "GOOGLE_DOC",
      googleUrl: "https://docs.google.com/document/d/1_iap_plan/edit",
      phaseId: "FASE_4",
      stageId: null,
      order: 0,
      activityKey: null,
      submissionMode: "EXTERNAL_LINK",
      optional: false,
      triggerCondition: "SEQUENTIAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: false,
      criticalTask: false,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_iap_plan",
    },

    // Itinerario VINCULACION (orden 1-5)
    {
      name: "Primer encuentro. Reflexión personal del PER.",
      description: "Reflexión personal del PER sobre el primer encuentro con la persona acompañada",
      type: "MANUAL_TASK",
      googleUrl: null,
      phaseId: "FASE_4",
      stageId: "VINCULACION",
      order: 1,
      activityKey: "PRIMER_ENCUENTRO_REFLEXION",
      submissionMode: "NATIVE_FORM",
      optional: false,
      triggerCondition: "SEQUENTIAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: true,
      criticalTask: false,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_primer_encuentro_reflexion",
      defaultDueDays: 7,
    },
    {
      name: "Actividad 1: Motivaciones y expectativas del acompañado",
      description: "Motivaciones y expectativas de la persona acompañada frente al proceso",
      type: "MANUAL_TASK",
      googleUrl: null,
      phaseId: "FASE_4",
      stageId: "VINCULACION",
      order: 2,
      activityKey: "ACTIVIDAD_1_MOTIVACIONES",
      submissionMode: "NATIVE_FORM",
      optional: false,
      triggerCondition: "SEQUENTIAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: true,
      criticalTask: false,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_actividad_1",
      defaultDueDays: 15,
    },
    {
      name: "Actividad 2: Guía para la exploración de antecedentes y contexto personal",
      description: "Exploración de antecedentes familiares, de salud, sociales y educacionales/laborales",
      type: "MANUAL_TASK",
      googleUrl: null,
      phaseId: "FASE_4",
      stageId: "VINCULACION",
      order: 3,
      activityKey: "ACTIVIDAD_2_ANTECEDENTES",
      submissionMode: "NATIVE_FORM",
      optional: false,
      triggerCondition: "SEQUENTIAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: true,
      criticalTask: false,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_actividad_2",
      defaultDueDays: 15,
    },
    {
      name: "Actividad 3: Mapa de recursos y necesidades",
      description: "Necesidades, fortalezas e importancia por cada uno de los 9 ámbitos de recuperación",
      type: "MANUAL_TASK",
      googleUrl: null,
      phaseId: "FASE_4",
      stageId: "VINCULACION",
      order: 4,
      activityKey: "ACTIVIDAD_3_MAPA_RECURSOS",
      submissionMode: "NATIVE_FORM",
      optional: false,
      triggerCondition: "SEQUENTIAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: true,
      criticalTask: true,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_actividad_3",
      defaultDueDays: 20,
    },
    {
      name: "Actividad 4: Planificación de objetivos y acciones",
      description: "Objetivos, recursos, actividades y plazos por ámbito de recuperación",
      type: "MANUAL_TASK",
      googleUrl: null,
      phaseId: "FASE_4",
      stageId: "VINCULACION",
      order: 5,
      activityKey: "ACTIVIDAD_4_PLANIFICACION",
      submissionMode: "NATIVE_FORM",
      optional: false,
      triggerCondition: "SEQUENTIAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: true,
      criticalTask: true,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_actividad_4",
      defaultDueDays: 20,
    },

    // Itinerario CONEXION
    {
      name: "Actividad 5: Evaluación conjunta del proceso (Intermedia)",
      description: "Evaluación intermedia del proceso de acompañamiento",
      type: "MANUAL_TASK",
      googleUrl: null,
      phaseId: "FASE_4",
      stageId: "CONEXION",
      order: 1,
      activityKey: "ACTIVIDAD_5_INTERMEDIA",
      submissionMode: "NATIVE_FORM",
      optional: false,
      triggerCondition: "SEQUENTIAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: false,
      criticalTask: false,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_evaluacion_intermedia",
      defaultDueDays: 30,
    },
    {
      name: "Reformular Actividad 4: Planificación de objetivos y acciones",
      description: "Reformulación del plan de trabajo según resultado de la Evaluación Intermedia (solo si aplica)",
      type: "MANUAL_TASK",
      googleUrl: null,
      phaseId: "FASE_4",
      stageId: "CONEXION",
      order: 2,
      activityKey: "REFORMULAR_ACTIVIDAD_4",
      submissionMode: "NATIVE_FORM",
      optional: true,
      triggerCondition: "SEQUENTIAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: false,
      blocksProgress: false,
      criticalTask: false,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_reformular_actividad_4",
      defaultDueDays: 15,
    },

    // Itinerario FINALIZACION
    {
      name: "Actividad 5: Evaluación conjunta del proceso (Final)",
      description: "Evaluación final / diagnóstica ex-post",
      type: "MANUAL_TASK",
      googleUrl: null,
      phaseId: "FASE_5",
      stageId: "FINALIZACION",
      order: 1,
      activityKey: "ACTIVIDAD_5_FINAL",
      submissionMode: "NATIVE_FORM",
      optional: false,
      triggerCondition: "SEQUENTIAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: true,
      criticalTask: true,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_evaluacion_ex_post",
      defaultDueDays: 15,
    },
    {
      name: "Actividad 6: Reflexiones finales del PER",
      description: "Reflexiones finales del PER sobre el proceso de acompañamiento",
      type: "MANUAL_TASK",
      googleUrl: null,
      phaseId: "FASE_5",
      stageId: "FINALIZACION",
      order: 2,
      activityKey: "ACTIVIDAD_6_REFLEXION_FINAL",
      submissionMode: "NATIVE_FORM",
      optional: false,
      triggerCondition: "SEQUENTIAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: true,
      criticalTask: false,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_actividad_6",
      defaultDueDays: 10,
    },
    {
      name: "Encuesta de Satisfacción PA",
      description: "Evaluación de calidad y satisfacción del proceso",
      type: "GOOGLE_FORM",
      googleUrl: "https://docs.google.com/forms/d/e/1FAIpQLSf789_satisfaccion/viewform",
      phaseId: "FASE_5",
      stageId: "FINALIZACION",
      order: 3,
      activityKey: "ENCUESTA_SATISFACCION",
      submissionMode: "EXTERNAL_LINK",
      optional: false,
      triggerCondition: "SEQUENTIAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: false,
      criticalTask: false,
      validationRequired: false,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_satisfaccion",
      defaultDueDays: 10,
    },

    // Formularios de abandono (condicionales, ON_WITHDRAWAL) — se materializan bajo demanda
    {
      name: "Formulario de Abandono — Persona Acompañada",
      description: "Registro oficial de retiro/deserción de la persona acompañada",
      type: "MANUAL_TASK",
      googleUrl: null,
      phaseId: "TRANSVERSAL",
      stageId: "FINALIZACION",
      order: 0,
      activityKey: "FORMULARIO_ABANDONO_PA",
      submissionMode: "NATIVE_FORM",
      optional: false,
      triggerCondition: "ON_WITHDRAWAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.1",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: false,
      criticalTask: false,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_retiro",
      defaultDueDays: 7,
    },
    {
      name: "Formulario de Abandono — PER",
      description: "Registro oficial de abandono del proceso por parte del PER",
      type: "MANUAL_TASK",
      googleUrl: null,
      phaseId: "TRANSVERSAL",
      stageId: "FINALIZACION",
      order: 0,
      activityKey: "FORMULARIO_ABANDONO_PER",
      submissionMode: "NATIVE_FORM",
      optional: false,
      triggerCondition: "ON_WITHDRAWAL",
      targetRole: "PER",
      scope: "NACIONAL",
      version: "1.0",
      status: "VIGENTE",
      mandatory: true,
      blocksProgress: false,
      criticalTask: false,
      validationRequired: true,
      createdByUserId,
      effectiveFrom: EFFECTIVE_FROM,
      templateFileId: "mock_template_retiro_per",
      defaultDueDays: 7,
    },
  ];
}
